import type { Metadata } from "next";
import {
    Bodoni_Moda,
    Geist,
    Geist_Mono,
    Luxurious_Script,
} from "next/font/google";
import "./globals.css";

const bodoniModa = Bodoni_Moda({
    variable: "--font-bodoni-moda",
    subsets: ["latin"],
});

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const luxuriousScript = Luxurious_Script({
    variable: "--font-luxurious-script",
    subsets: ["latin"],
    weight: '400',
});

export const metadata: Metadata = {
    title: "Hair Insider",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body
                className={`
                    ${bodoniModa.variable}
                    ${geistSans.variable}
                    ${geistMono.variable}
                    ${luxuriousScript.variable}
                    antialiased
                `}>
                {children}
            </body>
        </html>
    );
}
