import type { Metadata } from "next";
import { Bodoni_Moda, Luxurious_Script } from "next/font/google";
import "./globals.css";

const bodoniModa = Bodoni_Moda({
    variable: "--font-bodoni-moda",
    subsets: ["latin"],
    weight: ['400', '500', '600', '700', '800', '900'],
});

const luxuriousScript = Luxurious_Script({
    variable: "--font-luxurious-script",
    subsets: ["latin"],
    weight: "400",
});

export const metadata: Metadata = {
    title: "The Hair Insider",
    description: "Generated by create next app",
    icons: {
        icon: [{ url: "/favicon.ico" }],
        apple: [{ url: "/apple-touch-icon.png" }],
    },
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang='en'
            className={`
                ${bodoniModa.variable}
                ${luxuriousScript.variable}
            `}
            suppressHydrationWarning>
            <body className={`
                antialiased
                ${bodoniModa.className}
            `}>
                {children}
            </body>
        </html>
    );
}
